# Generated by Django 5.1 on 2024-09-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_post_image_post_comments_post_is_private_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='comments_count',
        ),
    ]
