# Generated by Django 5.1 on 2024-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userdata_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='api.userdata'),
        ),
    ]
