# Generated by Django 5.1 on 2024-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userdata_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='api.userdata'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to='api.userdata'),
        ),
    ]
