# Generated by Django 5.1 on 2024-09-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_userdata_followers_alter_userdata_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='friends',
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.userdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='api.userdata')),
            ],
            options={
                'unique_together': {('user', 'follower')},
            },
        ),
    ]
