# Generated by Django 5.1 on 2024-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_userdata_followers_remove_userdata_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='friends',
            field=models.ManyToManyField(blank=True, to='api.userdata'),
        ),
    ]
