# Generated by Django 5.1 on 2024-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
