# Generated by Django 5.1 on 2024-09-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notification_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('tag', 'Tag')], max_length=20),
        ),
    ]
