# Generated by Django 5.1 on 2024-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_comment_likes_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='banner_picture_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='banner_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='displayname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_picture_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
