# Generated by Django 5.1 on 2024-10-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userdata_banner_picture_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
