# Generated by Django 5.1 on 2024-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userdata_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
