# Generated by Django 5.1 on 2024-12-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_hiddenmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
